version: '3.9'
services:
  server-app:
    container_name: game-server-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5157:5157"
    depends_on:
      - postgres
    command: sh -c "dotnet ef database update && dotnet /app/build/GameServer.dll"
  
  postgres:
    container_name: game-server-postgres
    image: postgres
    environment:
      POSTGRES_USER: macbookair
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: game
    ports:
      - "5432:5432"
  
  nginx:
    container_name: game-server-nginx
    image: nginx
    volumes:
      - ./nginx/nginx.prod.conf:/etc/nginx/nginx.conf
      - /home/poorman/dist:/home/client/dist
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
      - ../../js/poorman/dist:/client-app
      - ../../js/poorman/src/assets:/client-app/assets-volumes
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - server-app
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  certbot:
    container_name: game-server-certbot
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"