// <auto-generated />
using System;
using GameServer.Postgres;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GameServer.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230524150853_AddPlayer")]
    partial class AddPlayer
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GameServer.Postgres.Models.Lobby", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasAnnotation("Relational:JsonPropertyName", "Id");

                    b.Property<int>("EndedTurnUsers")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "EndedTurnUsers");

                    b.Property<int>("JoinedUsers")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "JoinedUsers");

                    b.Property<int>("LoadedUsers")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "LoadedUsers");

                    b.Property<int>("TimerLeft")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "TimerLeft");

                    b.HasKey("Id");

                    b.ToTable("Lobby");
                });

            modelBuilder.Entity("GameServer.Postgres.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "Name");

                    b.HasKey("Id");

                    b.ToTable("Player");
                });
#pragma warning restore 612, 618
        }
    }
}
